### PR TITLE
yamlpatch: apply newline to EOF consistently

### LINKED ISSUE #1370: 1.17.0: Test test_preserve_trailing_newline_replace_multiline_at_end failing on openSUSE with
Dear maintainers,

I just tried to update the openSUSE package for zizmor, but the tests fail.

```
[  600s] test test_step_content_end_detection ... ok                                                                                                                                                                                                         
[  600s] test test_yaml_patch_replace_preserves_comments ... ok                                                                                                                                                                                              
[  600s] test test_preserve_trailing_newline_replace_multiline_at_end ... FAILED                                                                                                                                                                             
[  600s]                                                                                                                      
[  600s] failures:                                                                                                                                                                                                                                           
[  600s]                                                                                                                                                                                                                                                     
[  600s] ---- test_preserve_trailing_newline_replace_multiline_at_end stdout ----                                                                                                                                                                            
[  600s] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━                                                                                                                                                                    
[  600s] Snapshot: preserve_trailing_newline_replace_multiline_at_end                                                         
[  600s] Source: crates/yamlpatch/tests/unit_tests.rs:2528                                                                                                                                                                                                   
[  600s] ────────────────────────────────────────────────────────────────────────────────                                     
[  600s] Expression: result.source()                                                                                          
[  600s] ────────────────────────────────────────────────────────────────────────────────                                                                                                                                                                    
[  600s] -old snapshot                                                                                                                                                                                                                                       
[  600s] +new results                                                                                                         
[  600s] ────────────┬───────────────────────────────────────────────────────────────────                                                                                                                                                                    
[  600s]     1       │-        description: New description                                                                                                                                                                                                  
[  600s]           1 │+description: New description
[  600s] ────────────┴───────────────────────────────────────────────────────────────────
[  600s] To update snapshots run `cargo insta review`                                                                         
[  600s] Stopped on the first failure. Run `cargo insta test` to run all snapshots.                                                                                                                                                                          
[  600s]                                                                                                                      
[  600s] thread 'test_preserve_trailing_newline_replace_multiline_at_end' (33416) panicked at /home/abuild/rpmbuild/BUILD/zizmor-1.17.0-build/zizmor-1.17.0/vendor/insta-1.44.1/src/runtime.rs:689:13:
[  600s] snapshot assertion for 'preserve_trailing_newline_replace_multiline_at_end' failed in line 2528                      
[  600s] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                                                       
[  600s]                           
[  600s]                                                                                                                                                                                                                                                     
[  600s] failures:              
[  600s]     test_preserve_trailing_newline_replace_multiline_at_end
[  600s]                                                                                                                      
[  600s] test result: FAILED. 60 passed; 1 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.06s                   
[  600s]                                                
[  600s] error: test failed, to rerun pass `-p yamlpatch --test unit_tests`                                                                                                                                                                                  
[  600s]      Running unittests src/lib.rs (target/debug/deps/yamlpath-7b3923d5c492201b)
```

Any ideas why this fails? In case you need more details, feel free to reach out.

The build is using rust1.91, in case this is of interest.

Kind Regards,
Johannes

### PR DESCRIPTION
**Pull request by woodruffw**
Follows #1323. Fixes #1370.

### CODE REVIEW

File: crates/yamlpatch/src/lib.rs [hunk 1]
```diff
@@ -495,9 +463,16 @@ fn apply_single_patch(
...
             result.replace_range(start_pos..end_pos, "");
-            yamlpath::Document::new(result).map_err(Error::from)
+
+            result
         }
+    };
+
+    if !patched_content.ends_with('\n') {
+        patched_content.push('\n');
     }
```
Comment (woodruffw) [inline crates/yamlpatch/src/lib.rs:473]: This is the main change: instead of trying to preserve a newline in a replacement span, we now unconditionally insert one at EOF if not already present.

This ends up being an overproduction if a patch doesn't span the EOF, but it's a strictly correct one.

File: crates/yamlpatch/src/lib.rs [hunk 2]
```diff
@@ -209,42 +209,13 @@ pub fn apply_yaml_patches(
...
-    let start = byte_span.0;
-    let mut end = byte_span.1;
-    let content = document.source();
-
-    // Only include trailing newline if it's the last character in the document.
-    // This preserves document-level trailing newlines without interfering with
-    // newlines that are part of the document structure.
-    if end + 1 == content.len() && content.as_bytes()[end] == b'\n' {
-        end += 1;
-    }
```
Comment (woodruffw) [inline crates/yamlpatch/src/lib.rs:227]: I didn't try to prove it out, but I think the reason this didn't work is because some incoming patches _didn't_ have a trailing newline, and so if `tree-sitter-yaml` didn't include one in the captured node for whatever reason we'd end up trimming it.
